@startuml
title Tetris Multiplayer

actor User
participant "Screen" as screen
participant "NetworkManager" as network
participant "Server" as server

User -> screen : Connect - [IP]

screen --> network : SendConnectionRequest
network --> server : Request
server --> network : Response
network --> screen : OnConnectEvent(IP)
screen --> User : "Success Message"

@enduml
